# Generated by Django 3.1.7 on 2021-03-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img_gallarie', verbose_name='Photo')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date & Time')),
            ],
        ),
    ]
